/* server/host/common/assets_editor.h -- the per-client remapping editor
 * page: GET /editor?slot=N (server/host/common/webui.h). Split out of
 * assets.h once that page would otherwise cross ~1500 lines of literal
 * (assets.h's own top comment) -- same header-only reasoning, same
 * no-dependency, no-server-templating rules: every piece of state comes
 * from the JSON API at fetch time (GET /api/state to resolve the slot's
 * current profile name, GET /api/profile/{name} for the full profile, PUT
 * to save, POST /api/client/{slot}/profile to bind a fresh duplicate).
 *
 * Editor v1 (buttons, sticks, triggers) and v2 (touch regions, gyro) share
 * this one page and one profile-shaped JS object (PROFILE) that is mutated
 * in place as the operator edits controls, then serialised back out
 * verbatim on Save/Duplicate -- the exact same "GET response is already a
 * valid PUT body" property server/host/common/profile_json.h documents.
 *
 * Nothing here reimplements server/src/mapping.c or profiles.c: every field
 * this page edits is a plain value in the JSON profiles.c already reads
 * (deadzone, curve, invert, touch mode, gyro mode, ...); no curve math, no
 * deadzone application, no touch/gyro resolution happens client-side. The
 * only computed thing this page does is drawing -- the stick dot and the
 * touch-region canvas, both pure display of numbers the server already
 * computed or stored.
 *
 * SIGN CONVENTIONS (docs/PROTOCOL.md §5.3/§5.4, and see the matching note
 * on the GET /api/client/{slot}/input route in webui.h): lx/ly/rx/ry are
 * the STICK convention, +Y UP; touch region rects and the touch canvas are
 * the TOUCH convention, +Y DOWN. drawStick() negates Y before plotting
 * (pixel space is +Y down, so a +Y-up value needs the flip); the touch
 * region canvas applies NO flip at all, because +Y-down data plotted into
 * +Y-down pixel space already agrees. Getting this backwards would silently
 * mirror one axis of one of the two -- see each function's own comment
 * in the script below.
 */
#ifndef ATTICPAD_HOST_COMMON_ASSETS_EDITOR_H
#define ATTICPAD_HOST_COMMON_ASSETS_EDITOR_H

static const char ATTICPAD_EDITOR_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>AtticPad -- Customize profile</title>\n"
"<style>\n"
"  :root { color-scheme: dark light; }\n"
"  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0;\n"
"         background: #14161a; color: #e6e6e6; }\n"
"  header { padding: 16px 20px; background: #1c1f26; border-bottom: 1px solid #2a2e37; }\n"
"  header a.back { color: #7fd0ff; text-decoration: none; font-size: 13px; }\n"
"  h1 { font-size: 18px; margin: 6px 0 4px 0; }\n"
"  main { padding: 16px 20px; max-width: 960px; margin: 0 auto; }\n"
"  section { background: #1c1f26; border: 1px solid #2a2e37; border-radius: 8px;\n"
"            padding: 14px 16px; margin-bottom: 16px; }\n"
"  section h2 { font-size: 14px; text-transform: uppercase; letter-spacing: .04em;\n"
"               color: #9aa0aa; margin: 0 0 10px 0; }\n"
"  section h3 { font-size: 13px; margin: 0 0 8px 0; color: #e6e6e6; }\n"
"  table { width: 100%; border-collapse: collapse; font-size: 13px; }\n"
"  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #2a2e37; }\n"
"  .ok { color: #6fd88a; } .bad { color: #ff8a8a; } .muted { color: #9aa0aa; }\n"
"  button { background: #2d6fe0; color: white; border: none; border-radius: 6px;\n"
"           padding: 6px 12px; cursor: pointer; font-size: 13px; }\n"
"  button.secondary { background: #3a3f4b; }\n"
"  button:disabled { opacity: .5; cursor: default; }\n"
"  select, input[type=number] { background: #101215; color: #e6e6e6; border: 1px solid #2a2e37;\n"
"           border-radius: 4px; padding: 3px 6px; }\n"
"  input[type=range] { vertical-align: middle; }\n"
"  label { display: inline-block; margin: 4px 14px 4px 0; font-size: 13px; }\n"
"  #editorMsg { min-height: 18px; font-size: 13px; margin-bottom: 8px; }\n"
"  #buttonGrid tr.flash td { background: #F5B042; color: #1c212b; transition: background 0.4s; }\n"
"  .stick-cols { display: flex; gap: 28px; flex-wrap: wrap; }\n"
"  .stick-col canvas { background: #101215; border-radius: 6px; display: block; margin-bottom: 8px; }\n"
"  .touch-canvas { position: relative; width: 300px; height: 300px; background: #101215;\n"
"                  border: 1px solid #2a2e37; border-radius: 6px; margin-bottom: 10px;\n"
"                  overflow: hidden; }\n"
"  .touch-region { position: absolute; border: 2px solid #7fd0ff; background: rgba(127,208,255,0.15);\n"
"                  box-sizing: border-box; cursor: move; font-size: 11px; color: #7fd0ff; }\n"
"  .touch-region .handle { position: absolute; right: -5px; bottom: -5px; width: 10px; height: 10px;\n"
"                  background: #7fd0ff; cursor: nwse-resize; border-radius: 2px; }\n"
"  .touch-region .rlabel { position: absolute; top: 2px; left: 4px; pointer-events: none; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <a class=\"back\" href=\"/\">&larr; AtticPad</a>\n"
"  <h1>Customize profile</h1>\n"
"  <div id=\"deviceLabel\" class=\"muted\">--</div>\n"
"</header>\n"
"<main id=\"editorRoot\">\n"
"  <div id=\"editorMsg\"></div>\n"
"  <section>\n"
"    <div id=\"profileHeader\">loading&hellip;</div>\n"
"  </section>\n"
"  <section>\n"
"    <h2>Buttons</h2>\n"
"    <table id=\"buttonGrid\"><thead><tr>\n"
"      <th>Wire button</th><th>Sends</th><th></th>\n"
"    </tr></thead><tbody></tbody></table>\n"
"  </section>\n"
"  <section>\n"
"    <h2>Sticks</h2>\n"
"    <div class=\"stick-cols\">\n"
"      <div class=\"stick-col\">\n"
"        <h3>Left stick</h3>\n"
"        <canvas id=\"stickCanvasL\" width=\"140\" height=\"140\"></canvas>\n"
"        <label>Deadzone <span id=\"dzLLabel\">0%</span><br><input type=\"range\" id=\"dzL\" min=\"0\" max=\"0.4\" step=\"0.01\"></label><br>\n"
"        <label>Curve <select id=\"curveL\"></select></label><br>\n"
"        <label><input type=\"checkbox\" id=\"invxL\"> Invert X</label>\n"
"        <label><input type=\"checkbox\" id=\"invyL\"> Invert Y</label>\n"
"      </div>\n"
"      <div class=\"stick-col\">\n"
"        <h3>Right stick</h3>\n"
"        <canvas id=\"stickCanvasR\" width=\"140\" height=\"140\"></canvas>\n"
"        <label>Deadzone <span id=\"dzRLabel\">0%</span><br><input type=\"range\" id=\"dzR\" min=\"0\" max=\"0.4\" step=\"0.01\"></label><br>\n"
"        <label>Curve <select id=\"curveR\"></select></label><br>\n"
"        <label><input type=\"checkbox\" id=\"invxR\"> Invert X</label>\n"
"        <label><input type=\"checkbox\" id=\"invyR\"> Invert Y</label>\n"
"      </div>\n"
"    </div>\n"
"  </section>\n"
"  <section>\n"
"    <h2>Triggers</h2>\n"
"    <label>Deadzone <span id=\"dzTLabel\">0%</span><br><input type=\"range\" id=\"dzT\" min=\"0\" max=\"0.4\" step=\"0.01\"></label>\n"
"  </section>\n"
"  <section>\n"
"    <h2>Touch</h2>\n"
"    <label>Mode <select id=\"touchMode\">\n"
"      <option value=\"none\">None</option>\n"
"      <option value=\"regions\">Regions</option>\n"
"      <option value=\"delta_stick\">Delta stick</option>\n"
"      <option value=\"absolute_stick\">Absolute stick</option>\n"
"    </select></label>\n"
"    <div id=\"touchRegionsBox\" style=\"display:none;margin-top:10px\">\n"
"      <div class=\"muted\" style=\"font-size:12px;margin-bottom:6px\">Normalized touch surface, top-left is (0,0), Y increases downward. Drag to move, drag the corner handle to resize.</div>\n"
"      <div id=\"touchCanvas\" class=\"touch-canvas\"></div>\n"
"      <button class=\"secondary\" onclick=\"addRegion()\">Add region</button>\n"
"      <table id=\"regionTable\" style=\"margin-top:10px\"><thead><tr>\n"
"        <th>Rect (x0,y0,x1,y1)</th><th>Target</th><th>Analog</th><th></th>\n"
"      </tr></thead><tbody></tbody></table>\n"
"    </div>\n"
"    <div id=\"touchStickBox\" style=\"display:none;margin-top:10px\">\n"
"      <label>Stick <select id=\"touchStick\"><option value=\"left\">Left</option><option value=\"right\">Right</option></select></label><br>\n"
"      <label>Sensitivity <input type=\"number\" id=\"touchSens\" step=\"0.1\" min=\"0\" style=\"width:70px\"></label><br>\n"
"      <label>Deadzone <span id=\"touchDzLabel\">0%</span><br><input type=\"range\" id=\"touchDz\" min=\"0\" max=\"0.4\" step=\"0.01\"></label><br>\n"
"      <label><input type=\"checkbox\" id=\"touchInvX\"> Invert X</label>\n"
"      <label><input type=\"checkbox\" id=\"touchInvY\"> Invert Y</label>\n"
"    </div>\n"
"  </section>\n"
"  <section>\n"
"    <h2>Gyro</h2>\n"
"    <label>Mode <select id=\"gyroMode\">\n"
"      <option value=\"none\">Off</option>\n"
"      <option value=\"substitute\">Replaces a stick</option>\n"
"      <option value=\"aim\">Adds to aiming</option>\n"
"    </select></label>\n"
"    <div id=\"gyroBox\" style=\"display:none;margin-top:10px\">\n"
"      <label>Stick <select id=\"gyroStick\"><option value=\"left\">Left</option><option value=\"right\">Right</option></select></label><br>\n"
"      <label>X axis <select id=\"gyroAxisX\"></select></label>\n"
"      <label>Y axis <select id=\"gyroAxisY\"></select></label><br>\n"
"      <label>Sensitivity <input type=\"number\" id=\"gyroSens\" step=\"0.1\" min=\"0\" style=\"width:70px\"></label><br>\n"
"      <label>Deadzone <span id=\"gyroDzLabel\">0%</span><br><input type=\"range\" id=\"gyroDz\" min=\"0\" max=\"0.4\" step=\"0.01\"></label><br>\n"
"      <label><input type=\"checkbox\" id=\"gyroInvX\"> Invert X</label>\n"
"      <label><input type=\"checkbox\" id=\"gyroInvY\"> Invert Y</label>\n"
"    </div>\n"
"  </section>\n"
"</main>\n"
"<script>\n"
"var SLOT = null;\n"
"var PROFILE = null;\n"
"var CAPTURE_ARMED = false;\n"
"var LAST_BUTTONS = 0;\n"
"var POLL_TIMER = null;\n"
"var DRAG = null;\n"
"\n"
"var WIRE_BUTTONS = [\"A\",\"B\",\"X\",\"Y\",\"L\",\"R\",\"L3\",\"R3\",\"START\",\"SELECT\",\"HOME\"];\n"
"var WIRE_BITS    = [0x1,0x2,0x4,0x8,0x100,0x200,0x1000,0x2000,0x4000,0x8000,0x10000];\n"
"var PAD_TARGETS  = [\"NONE\",\"A\",\"B\",\"X\",\"Y\",\"LB\",\"RB\",\"BACK\",\"START\",\"GUIDE\",\"LTHUMB\",\"RTHUMB\"];\n"
"var TOUCH_TARGETS = [\"NONE\",\"LT\",\"RT\",\"A\",\"B\",\"X\",\"Y\",\"LB\",\"RB\",\"BACK\",\"START\",\"GUIDE\",\"LTHUMB\",\"RTHUMB\"];\n"
"var CURVES = [\"linear\",\"quadratic\",\"cubic\"];\n"
"var AXES = [\"pitch\",\"roll\",\"yaw\"];\n"
"var MAX_REGIONS = 8;\n"
"\n"
"function esc(s) { return String(s).replace(/[&<>\"]/g, function(c){\n"
"  return { '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;' }[c]; }); }\n"
"\n"
"function clamp1(v) { return Math.max(-1, Math.min(1, v)); }\n"
"\n"
"function msg(html, cls) {\n"
"  document.getElementById('editorMsg').innerHTML = cls ? ('<span class=\"' + cls + '\">' + html + '</span>') : html;\n"
"}\n"
"\n"
"function fatal(text) {\n"
"  document.getElementById('editorRoot').innerHTML = '<div class=\"bad\">' + esc(text) + '</div>';\n"
"}\n"
"\n"
"/* ---- boot: resolve ?slot=N -> the client's current profile -------------- */\n"
"\n"
"function init() {\n"
"  var params = new URLSearchParams(location.search);\n"
"  SLOT = parseInt(params.get('slot'), 10);\n"
"  if (isNaN(SLOT)) { fatal('no slot given (open this page from the Customize button)'); return; }\n"
"  loadFromState();\n"
"}\n"
"\n"
"function loadFromState() {\n"
"  fetch('/api/state').then(function(r){ return r.json(); }).then(function(s){\n"
"    var c = null, i;\n"
"    for (i = 0; i < s.clients.length; i++) { if (s.clients[i].slot === SLOT) { c = s.clients[i]; break; } }\n"
"    if (!c) { fatal('no device connected on slot ' + SLOT); return; }\n"
"    document.getElementById('deviceLabel').textContent = c.device_name + ' (slot ' + SLOT + ')';\n"
"    loadProfile(c.profile);\n"
"  }).catch(function(){ fatal('could not reach the server'); });\n"
"}\n"
"\n"
"function loadProfile(name) {\n"
"  fetch('/api/profile/' + encodeURIComponent(name)).then(function(r){\n"
"    if (!r.ok) { throw new Error('not found'); }\n"
"    return r.json();\n"
"  }).then(function(p){\n"
"    PROFILE = p;\n"
"    render();\n"
"  }).catch(function(){ fatal('could not load profile \"' + name + '\"'); });\n"
"}\n"
"\n"
"/* ---- render: fills the static form from PROFILE, once per profile load -- */\n"
"\n"
"function render() {\n"
"  msg('');\n"
"  renderHeader();\n"
"  renderButtons();\n"
"  renderSticks();\n"
"  renderTriggers();\n"
"  renderTouch();\n"
"  renderGyro();\n"
"  startPoll();\n"
"}\n"
"\n"
"function renderHeader() {\n"
"  var h = document.getElementById('profileHeader');\n"
"  var match = (PROFILE.match && PROFILE.match.device) ? esc(PROFILE.match.device) : '<span class=\"muted\">any device</span>';\n"
"  var html = '<div><b>' + esc(PROFILE.profile) + '</b> <span class=\"muted\">matches: ' + match + '</span></div>';\n"
"  if (!PROFILE.editable) {\n"
"    html += '<div class=\"muted\" style=\"margin-top:6px\">Read-only profile &mdash; duplicate to customize</div>';\n"
"    html += '<div style=\"margin-top:8px\"><button onclick=\"duplicateProfile()\">Duplicate &amp; customize</button></div>';\n"
"  } else {\n"
"    html += '<div style=\"margin-top:8px\"><button onclick=\"saveProfile()\">Save</button></div>';\n"
"  }\n"
"  h.innerHTML = html;\n"
"}\n"
"\n"
"function padTargetOptions(list, current) {\n"
"  return list.map(function(t){\n"
"    return '<option value=\"' + t + '\"' + (t === current ? ' selected' : '') + '>' + t + '</option>';\n"
"  }).join('');\n"
"}\n"
"\n"
"function renderButtons() {\n"
"  var tbody = document.querySelector('#buttonGrid tbody');\n"
"  tbody.innerHTML = WIRE_BUTTONS.map(function(w, i){\n"
"    var cur = PROFILE.buttons[w] || 'NONE';\n"
"    return '<tr id=\"wireRow' + i + '\"><td>' + w + '</td>' +\n"
"      '<td><select id=\"wireSel' + i + '\">' + padTargetOptions(PAD_TARGETS, cur) + '</select></td>' +\n"
"      '<td><button class=\"secondary\" onclick=\"armCapture(event)\">Press it</button></td></tr>';\n"
"  }).join('');\n"
"  WIRE_BUTTONS.forEach(function(w, i){\n"
"    document.getElementById('wireSel' + i).addEventListener('change', function(){\n"
"      PROFILE.buttons[w] = this.value;\n"
"    });\n"
"  });\n"
"}\n"
"\n"
"/* ---- capture: \"Press it\" arms a listener over the next ~poll or two ----- */\n"
"\n"
"function armCapture(e) {\n"
"  if (e) { e.stopPropagation(); }\n"
"  CAPTURE_ARMED = true;\n"
"  msg('listening for a button press&hellip; (Esc or click elsewhere to cancel)', 'muted');\n"
"}\n"
"\n"
"function disarmCapture() {\n"
"  CAPTURE_ARMED = false;\n"
"}\n"
"\n"
"document.addEventListener('keydown', function(e){\n"
"  if (e.key === 'Escape' && CAPTURE_ARMED) { disarmCapture(); msg(''); }\n"
"});\n"
"document.addEventListener('click', function(){\n"
"  if (CAPTURE_ARMED) { disarmCapture(); msg(''); }\n"
"});\n"
"\n"
"function highlightRow(i) {\n"
"  msg('detected: ' + WIRE_BUTTONS[i], 'ok');\n"
"  var row = document.getElementById('wireRow' + i);\n"
"  if (row) {\n"
"    row.classList.add('flash');\n"
"    setTimeout(function(){ row.classList.remove('flash'); }, 1200);\n"
"  }\n"
"}\n"
"\n"
"/* ---- sticks: deadzone/curve/invert form + live raw-position dot --------- */\n"
"\n"
"function renderSticks() { fillStick('L', PROFILE.sticks.left); fillStick('R', PROFILE.sticks.right); }\n"
"\n"
"function fillStick(suf, st) {\n"
"  document.getElementById('dz' + suf).value = st.deadzone;\n"
"  document.getElementById('dz' + suf + 'Label').textContent = Math.round(st.deadzone * 100) + '%';\n"
"  var sel = document.getElementById('curve' + suf);\n"
"  sel.innerHTML = CURVES.map(function(c){\n"
"    return '<option value=\"' + c + '\"' + (c === st.curve ? ' selected' : '') + '>' + c + '</option>';\n"
"  }).join('');\n"
"  document.getElementById('invx' + suf).checked = !!st.invert_x;\n"
"  document.getElementById('invy' + suf).checked = !!st.invert_y;\n"
"}\n"
"\n"
"function bindStick(suf, which) {\n"
"  document.getElementById('dz' + suf).addEventListener('input', function(){\n"
"    var v = parseFloat(this.value);\n"
"    PROFILE.sticks[which].deadzone = v;\n"
"    document.getElementById('dz' + suf + 'Label').textContent = Math.round(v * 100) + '%';\n"
"  });\n"
"  document.getElementById('curve' + suf).addEventListener('change', function(){ PROFILE.sticks[which].curve = this.value; });\n"
"  document.getElementById('invx' + suf).addEventListener('change', function(){ PROFILE.sticks[which].invert_x = this.checked; });\n"
"  document.getElementById('invy' + suf).addEventListener('change', function(){ PROFILE.sticks[which].invert_y = this.checked; });\n"
"}\n"
"bindStick('L', 'left');\n"
"bindStick('R', 'right');\n"
"\n"
"/* Raw position dot + deadzone ring, drawn from the SAME 15 Hz poll capture\n"
" * uses. SIGN CONVENTION: lx/ly/rx/ry from /api/client/{slot}/input are the\n"
" * STICK convention, +Y UP (unflipped from the wire -- webui.h's own\n"
" * comment on that route). Canvas pixel space is +Y DOWN, so the Y\n"
" * component is negated here; X needs no flip. This is the opposite\n"
" * convention from the touch canvas below, which uses +Y DOWN throughout\n"
" * with no flip at all -- see drawTouchDot() and that section's own note. */\n"
"function drawStick(canvasId, x, y, deadzone) {\n"
"  var cv = document.getElementById(canvasId);\n"
"  if (!cv || !cv.getContext) { return; }\n"
"  var ctx = cv.getContext('2d');\n"
"  var w = cv.width, h = cv.height, cx = w / 2, cy = h / 2, r = Math.min(w, h) / 2 - 8;\n"
"  ctx.clearRect(0, 0, w, h);\n"
"  ctx.strokeStyle = '#2a2e37';\n"
"  ctx.beginPath(); ctx.arc(cx, cy, r, 0, 2 * Math.PI); ctx.stroke();\n"
"  ctx.strokeStyle = '#3a3f4b';\n"
"  ctx.beginPath(); ctx.arc(cx, cy, r * deadzone, 0, 2 * Math.PI); ctx.stroke();\n"
"  var px = cx + clamp1(x) * r;\n"
"  var py = cy - clamp1(y) * r;   /* +Y UP (stick) -> pixel +Y DOWN: negate */\n"
"  ctx.fillStyle = '#7fd0ff';\n"
"  ctx.beginPath(); ctx.arc(px, py, 4, 0, 2 * Math.PI); ctx.fill();\n"
"}\n"
"\n"
"/* ---- triggers ------------------------------------------------------------ */\n"
"\n"
"function renderTriggers() {\n"
"  var v = PROFILE.triggers.deadzone;\n"
"  document.getElementById('dzT').value = v;\n"
"  document.getElementById('dzTLabel').textContent = Math.round(v * 100) + '%';\n"
"}\n"
"document.getElementById('dzT').addEventListener('input', function(){\n"
"  var v = parseFloat(this.value);\n"
"  PROFILE.triggers.deadzone = v;\n"
"  document.getElementById('dzTLabel').textContent = Math.round(v * 100) + '%';\n"
"});\n"
"\n"
"/* ---- touch: mode switch, delta/absolute-stick fields, region editor ----- */\n"
"\n"
"function renderTouch() {\n"
"  document.getElementById('touchMode').value = PROFILE.touch.mode;\n"
"  document.getElementById('touchStick').value = PROFILE.touch.stick;\n"
"  document.getElementById('touchSens').value = PROFILE.touch.sensitivity;\n"
"  document.getElementById('touchDz').value = PROFILE.touch.deadzone;\n"
"  document.getElementById('touchDzLabel').textContent = Math.round(PROFILE.touch.deadzone * 100) + '%';\n"
"  document.getElementById('touchInvX').checked = !!PROFILE.touch.invert_x;\n"
"  document.getElementById('touchInvY').checked = !!PROFILE.touch.invert_y;\n"
"  updateTouchVisibility();\n"
"  renderRegions();\n"
"}\n"
"\n"
"function updateTouchVisibility() {\n"
"  var mode = PROFILE.touch.mode;\n"
"  document.getElementById('touchRegionsBox').style.display = (mode === 'regions') ? '' : 'none';\n"
"  document.getElementById('touchStickBox').style.display =\n"
"    (mode === 'delta_stick' || mode === 'absolute_stick') ? '' : 'none';\n"
"}\n"
"\n"
"document.getElementById('touchMode').addEventListener('change', function(){\n"
"  PROFILE.touch.mode = this.value;\n"
"  updateTouchVisibility();\n"
"});\n"
"document.getElementById('touchStick').addEventListener('change', function(){ PROFILE.touch.stick = this.value; });\n"
"document.getElementById('touchSens').addEventListener('input', function(){ PROFILE.touch.sensitivity = parseFloat(this.value) || 0; });\n"
"document.getElementById('touchDz').addEventListener('input', function(){\n"
"  var v = parseFloat(this.value);\n"
"  PROFILE.touch.deadzone = v;\n"
"  document.getElementById('touchDzLabel').textContent = Math.round(v * 100) + '%';\n"
"});\n"
"document.getElementById('touchInvX').addEventListener('change', function(){ PROFILE.touch.invert_x = this.checked; });\n"
"document.getElementById('touchInvY').addEventListener('change', function(){ PROFILE.touch.invert_y = this.checked; });\n"
"\n"
"function addRegion() {\n"
"  if (PROFILE.touch.regions.length >= MAX_REGIONS) { return; }\n"
"  PROFILE.touch.regions.push({ rect: [0.1, 0.1, 0.4, 0.4], emit: 'NONE', analog: false });\n"
"  renderRegions();\n"
"}\n"
"function removeRegion(i) {\n"
"  PROFILE.touch.regions.splice(i, 1);\n"
"  renderRegions();\n"
"}\n"
"\n"
"function renderRegions() {\n"
"  var regions = PROFILE.touch.regions;\n"
"  var tbody = document.querySelector('#regionTable tbody');\n"
"  tbody.innerHTML = regions.map(function(r, i){\n"
"    return '<tr>' +\n"
"      '<td>' + r.rect.map(function(n){ return n.toFixed(2); }).join(', ') + '</td>' +\n"
"      '<td><select id=\"regTarget' + i + '\">' + padTargetOptions(TOUCH_TARGETS, r.emit) + '</select></td>' +\n"
"      '<td><input type=\"checkbox\" id=\"regAnalog' + i + '\"' + (r.analog ? ' checked' : '') + '></td>' +\n"
"      '<td><button class=\"secondary\" onclick=\"removeRegion(' + i + ')\">Remove</button></td></tr>';\n"
"  }).join('');\n"
"  regions.forEach(function(r, i){\n"
"    document.getElementById('regTarget' + i).addEventListener('change', function(){ r.emit = this.value; });\n"
"    document.getElementById('regAnalog' + i).addEventListener('change', function(){ r.analog = this.checked; });\n"
"  });\n"
"  drawTouchCanvas();\n"
"}\n"
"\n"
"/* Region rects are normalised 0..1, +Y DOWN -- the WIRE's touch convention\n"
" * (docs/PROTOCOL.md §5.3), unlike the stick dots above: no sign flip is\n"
" * applied anywhere in this section, on purpose, because the canvas here is\n"
" * ALSO +Y down (ordinary screen/CSS space) -- the two conventions happen to\n"
" * already agree, which is exactly why the stick section above needs a flip\n"
" * and this one does not. */\n"
"function drawTouchCanvas() {\n"
"  var box = document.getElementById('touchCanvas');\n"
"  box.innerHTML = '';\n"
"  var w = box.clientWidth || 300, h = box.clientHeight || 300;\n"
"  PROFILE.touch.regions.forEach(function(r, i){\n"
"    var el = document.createElement('div');\n"
"    el.className = 'touch-region';\n"
"    positionRegionEl(el, r, w, h);\n"
"    el.innerHTML = '<span class=\"rlabel\">' + esc(r.emit) + '</span><div class=\"handle\"></div>';\n"
"    el.addEventListener('mousedown', function(ev){ startDrag(ev, i, 'move'); });\n"
"    el.querySelector('.handle').addEventListener('mousedown', function(ev){\n"
"      ev.stopPropagation();\n"
"      startDrag(ev, i, 'resize');\n"
"    });\n"
"    box.appendChild(el);\n"
"  });\n"
"}\n"
"\n"
"function positionRegionEl(el, r, w, h) {\n"
"  var x0 = Math.min(r.rect[0], r.rect[2]), x1 = Math.max(r.rect[0], r.rect[2]);\n"
"  var y0 = Math.min(r.rect[1], r.rect[3]), y1 = Math.max(r.rect[1], r.rect[3]);\n"
"  el.style.left = (x0 * w) + 'px';\n"
"  el.style.top = (y0 * h) + 'px';\n"
"  el.style.width = Math.max(8, (x1 - x0) * w) + 'px';\n"
"  el.style.height = Math.max(8, (y1 - y0) * h) + 'px';\n"
"}\n"
"\n"
"function startDrag(ev, i, kind) {\n"
"  ev.preventDefault();\n"
"  var box = document.getElementById('touchCanvas');\n"
"  var rectPx = box.getBoundingClientRect();\n"
"  DRAG = { i: i, kind: kind, boxW: rectPx.width, boxH: rectPx.height, boxLeft: rectPx.left, boxTop: rectPx.top,\n"
"           start: PROFILE.touch.regions[i].rect.slice(), startX: ev.clientX, startY: ev.clientY };\n"
"}\n"
"document.addEventListener('mousemove', function(ev){\n"
"  if (!DRAG) { return; }\n"
"  var r = PROFILE.touch.regions[DRAG.i];\n"
"  var dx = (ev.clientX - DRAG.startX) / DRAG.boxW;\n"
"  var dy = (ev.clientY - DRAG.startY) / DRAG.boxH;\n"
"  if (DRAG.kind === 'move') {\n"
"    var w = DRAG.start[2] - DRAG.start[0], h = DRAG.start[3] - DRAG.start[1];\n"
"    var nx0 = clampFrac(DRAG.start[0] + dx), ny0 = clampFrac(DRAG.start[1] + dy);\n"
"    r.rect[0] = nx0; r.rect[1] = ny0;\n"
"    r.rect[2] = clampFrac(nx0 + w); r.rect[3] = clampFrac(ny0 + h);\n"
"  } else {\n"
"    r.rect[2] = clampFrac(DRAG.start[2] + dx);\n"
"    r.rect[3] = clampFrac(DRAG.start[3] + dy);\n"
"  }\n"
"  positionRegionEl(document.querySelectorAll('.touch-region')[DRAG.i], r, DRAG.boxW, DRAG.boxH);\n"
"});\n"
"document.addEventListener('mouseup', function(){\n"
"  if (DRAG) { DRAG = null; renderRegions(); }\n"
"});\n"
"function clampFrac(v) { return Math.max(0, Math.min(1, v)); }\n"
"\n"
"/* ---- gyro ----------------------------------------------------------------*/\n"
"\n"
"function axisOptions(current) {\n"
"  return AXES.map(function(a){ return '<option value=\"' + a + '\"' + (a === current ? ' selected' : '') + '>' + a + '</option>'; }).join('');\n"
"}\n"
"\n"
"function renderGyro() {\n"
"  var g = PROFILE.gyro;\n"
"  document.getElementById('gyroMode').value = g.mode;\n"
"  document.getElementById('gyroStick').value = g.stick;\n"
"  document.getElementById('gyroAxisX').innerHTML = axisOptions(g.axis_x);\n"
"  document.getElementById('gyroAxisY').innerHTML = axisOptions(g.axis_y);\n"
"  document.getElementById('gyroSens').value = g.sensitivity;\n"
"  document.getElementById('gyroDz').value = g.deadzone;\n"
"  document.getElementById('gyroDzLabel').textContent = Math.round(g.deadzone * 100) + '%';\n"
"  document.getElementById('gyroInvX').checked = !!g.invert_x;\n"
"  document.getElementById('gyroInvY').checked = !!g.invert_y;\n"
"  updateGyroVisibility();\n"
"}\n"
"function updateGyroVisibility() {\n"
"  document.getElementById('gyroBox').style.display = (PROFILE.gyro.mode === 'none') ? 'none' : '';\n"
"}\n"
"document.getElementById('gyroMode').addEventListener('change', function(){ PROFILE.gyro.mode = this.value; updateGyroVisibility(); });\n"
"document.getElementById('gyroStick').addEventListener('change', function(){ PROFILE.gyro.stick = this.value; });\n"
"document.getElementById('gyroAxisX').addEventListener('change', function(){ PROFILE.gyro.axis_x = this.value; });\n"
"document.getElementById('gyroAxisY').addEventListener('change', function(){ PROFILE.gyro.axis_y = this.value; });\n"
"document.getElementById('gyroSens').addEventListener('input', function(){ PROFILE.gyro.sensitivity = parseFloat(this.value) || 0; });\n"
"document.getElementById('gyroDz').addEventListener('input', function(){\n"
"  var v = parseFloat(this.value);\n"
"  PROFILE.gyro.deadzone = v;\n"
"  document.getElementById('gyroDzLabel').textContent = Math.round(v * 100) + '%';\n"
"});\n"
"document.getElementById('gyroInvX').addEventListener('change', function(){ PROFILE.gyro.invert_x = this.checked; });\n"
"document.getElementById('gyroInvY').addEventListener('change', function(){ PROFILE.gyro.invert_y = this.checked; });\n"
"\n"
"/* ---- save / duplicate ----------------------------------------------------*/\n"
"\n"
"function saveProfile() {\n"
"  fetch('/api/profile/' + encodeURIComponent(PROFILE.profile), {\n"
"    method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(PROFILE)\n"
"  }).then(function(r){\n"
"    if (r.ok) { msg('Saved &mdash; applied to connected devices', 'ok'); return null; }\n"
"    return r.json().then(function(b){ throw new Error(b.error || ('HTTP ' + r.status)); });\n"
"  }).catch(function(e){ msg('could not save: ' + esc(e.message), 'bad'); });\n"
"}\n"
"\n"
"function duplicateProfile() {\n"
"  var suggested = '00-' + PROFILE.profile;\n"
"  var name = window.prompt('Name for the new profile:', suggested);\n"
"  if (!name) { return; }\n"
"  fetch('/api/profile/' + encodeURIComponent(name), {\n"
"    method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(PROFILE)\n"
"  }).then(function(r){\n"
"    if (!r.ok) { return r.json().then(function(b){ throw new Error(b.error || ('HTTP ' + r.status)); }); }\n"
"    /* Bind the slot this editor is open for to the new copy, so\n"
"     * \"duplicate & customize\" actually takes effect for the device that\n"
"     * prompted it -- not just saved to disk with nothing using it yet. */\n"
"    return fetch('/api/client/' + SLOT + '/profile', {\n"
"      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ profile: name })\n"
"    });\n"
"  }).then(function(){\n"
"    msg('Duplicated as \"' + esc(name) + '\" &mdash; now editing the copy', 'ok');\n"
"    loadProfile(name);\n"
"  }).catch(function(e){ msg('could not duplicate: ' + esc(e.message), 'bad'); });\n"
"}\n"
"\n"
"/* ---- 15 Hz poll: capture edge-detection + live stick dots ---------------- */\n"
"\n"
"function startPoll() {\n"
"  if (POLL_TIMER) { clearInterval(POLL_TIMER); }\n"
"  LAST_BUTTONS = 0;\n"
"  POLL_TIMER = setInterval(pollInput, 67);\n"
"}\n"
"\n"
"function pollInput() {\n"
"  fetch('/api/client/' + SLOT + '/input').then(function(r){\n"
"    return r.ok ? r.json() : null;\n"
"  }).then(function(st){\n"
"    if (!st) { return; }\n"
"    if (CAPTURE_ARMED) {\n"
"      for (var i = 0; i < WIRE_BITS.length; i++) {\n"
"        var was = (LAST_BUTTONS & WIRE_BITS[i]) !== 0;\n"
"        var isNow = (st.buttons & WIRE_BITS[i]) !== 0;\n"
"        if (!was && isNow) { highlightRow(i); disarmCapture(); break; }\n"
"      }\n"
"    }\n"
"    LAST_BUTTONS = st.buttons;\n"
"    drawStick('stickCanvasL', st.lx / 32767, st.ly / 32767, PROFILE.sticks.left.deadzone);\n"
"    drawStick('stickCanvasR', st.rx / 32767, st.ry / 32767, PROFILE.sticks.right.deadzone);\n"
"  }).catch(function(){});\n"
"}\n"
"\n"
"init();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* ATTICPAD_HOST_COMMON_ASSETS_EDITOR_H */
