/* server/host/common/profiles_builtin.h -- GENERATED, do not edit.
 *
 * Source: the .jsonc files in server/profiles/
 * Regenerate: scripts/support/gen_profiles_builtin.py (scripts/build.sh
 * does it, and CI fails if the committed copy differs).
 *
 * Why these are compiled in: a release is a single binary, and a server
 * that finds no profiles on disk would otherwise fall back to the
 * built-in default -- which on a 3DS means no touch-region triggers and
 * no gyro aim, while the client still draws both. Files on disk still
 * win; these are only the floor.
 */
#ifndef ATTICPAD_HOST_COMMON_PROFILES_BUILTIN_H
#define ATTICPAD_HOST_COMMON_PROFILES_BUILTIN_H

typedef struct {
    const char *label;   /* for diagnostics: where this came from */
    const char *name;    /* profile file stem, as on disk         */
    const char *text;    /* the JSONC itself                      */
} apad_builtin_profile;

/* server/profiles/3ds-default.jsonc */
static const char ATTICPAD_PROFILE_3DS_DEFAULT[] =
"{\n"
"  // 3DS default profile. Matches any HELLO whose decoded device_name\n"
"  // contains \"3DS\" (server/src/profiles.c: apad_profiles_match() does a\n"
"  // plain substring test against the whole device_name field). This one\n"
"  // file now covers BOTH 3DS variants -- see the \"gyro\" section below for\n"
"  // why a second, separately-matched profile isn't needed.\n"
"  //\n"
"  // docs/DESIGN.md §6.2's own worked example is for the Old 3DS: \"no C-stick, so\n"
"  // gyro drives the right stick.\" A New 3DS (caps=0x000004EF in the field\n"
"  // report this profile was written against) advertises APAD_CAP_STICK_R\n"
"  // AND APAD_CAP_GYRO together -- a working C-stick plus a gyro that, under\n"
"  // the old substitute-only priority chain (physical stick > touch\n"
"  // substitute > gyro substitute > centred), was read off the wire, mapped,\n"
"  // and then silently discarded every time because the physical stick\n"
"  // always won. Gyro aim had never once affected the pad on that hardware.\n"
"  //\n"
"  // \"mode\": \"aim\" (server/src/profiles.h's apad_gyro_mode_t) fixes this:\n"
"  // gyro now ADDS to the C-stick's own output (clamped to the axis range)\n"
"  // instead of only substituting for a missing one. On an Old 3DS, which\n"
"  // never sets APAD_CAP_STICK_R, the \"physical\" side of that sum is 0, so\n"
"  // the sum is just the gyro alone -- numerically identical to the old\n"
"  // substitute-only behaviour (server/src/mapping.c's compute_stick()\n"
"  // comment has the proof). That equivalence is exactly why one profile,\n"
"  // not two, is correct here: a second \"3ds-gyro-aim.jsonc\" matched on the\n"
"  // same \"3DS\" substring would only ever be reached if it sorted before\n"
"  // this file's name (server/src/profiles.c's apad_profiles_match() takes\n"
"  // the FIRST loaded profile whose match_device matches, in filename-sorted\n"
"  // order) -- an ambiguity with no user-facing way to pick between them,\n"
"  // since device_name comes from client firmware, not a user setting. This\n"
"  // file resolves that by being the one and only 3DS profile, correct for\n"
"  // both consoles.\n"
"  \"profile\": \"3ds-default\",\n"
"  \"match\": { \"device\": \"3DS\" },\n"
"\n"
"  // Identity button naming (wire \"A\" -> pad \"A\", and so on), matching\n"
"  // docs/DESIGN.md §6.2's own example verbatim. This deliberately does NOT use\n"
"  // the protocol's default physical-position swap (docs/PROTOCOL.md §5.4:\n"
"  // wire A, the right-hand face button, -> Xbox B, the right-hand Xbox\n"
"  // button in a *different* physical slot than A) -- §5.4 explicitly\n"
"  // reserves that choice for a profile: \"Per-profile A/B and X/Y swapping\n"
"  // is a mapping concern, not a protocol concern.\" Every 3DS game tells\n"
"  // the player to \"press A\"; keeping the label the player already\n"
"  // associates with that physical button outweighs matching an Xbox pad's\n"
"  // own physical face-button layout.\n"
"  \"buttons\": {\n"
"    \"A\": \"A\", \"B\": \"B\", \"X\": \"X\", \"Y\": \"Y\",\n"
"    \"L\": \"LB\", \"R\": \"RB\"\n"
"    // L3/R3/START/SELECT/HOME are left at the built-in default mapping\n"
"    // (LTHUMB/RTHUMB/START/BACK/GUIDE) -- nothing 3DS-specific to say\n"
"    // about them, and a 3DS HELLO never sets the L3/R3 bits anyway (no\n"
"    // clickable sticks on the hardware).\n"
"  },\n"
"\n"
"  // Circle Pad -> left stick. 8% deadzone (a physical circle pad's rest\n"
"  // position drifts more than a modern digital stick's centring spring),\n"
"  // quadratic curve: gentle near centre for fine aiming, full deflection\n"
"  // still reachable at the physical edge of travel.\n"
"  \"sticks\": {\n"
"    \"deadzone\": 0.08,\n"
"    \"curve\": \"quadratic\"\n"
"  },\n"
"\n"
"  // Bottom touchscreen, split into two soft on-screen shoulder triggers:\n"
"  // left half of the screen drives LT, right half drives RT, both analog.\n"
"  // \"analog: true\" ramps pressure with how far the thumb slides into its\n"
"  // half (see server/src/profiles.h's apad_touch_region comment for the\n"
"  // exact \"depth-into-region\" definition this engine uses -- these rects\n"
"  // are taller than they are wide, so depth reads as vertical travel: a\n"
"  // soft downward slide feels like squeezing a real analog trigger).\n"
"  // This is docs/DESIGN.md §6.2's own worked example, reproduced here.\n"
"  \"touch\": {\n"
"    \"mode\": \"regions\",\n"
"    \"regions\": [\n"
"      { \"rect\": [0.0, 0.0, 0.5, 1.0], \"emit\": \"LT\", \"analog\": true },\n"
"      { \"rect\": [0.5, 0.0, 1.0, 1.0], \"emit\": \"RT\", \"analog\": true }\n"
"    ]\n"
"  },\n"
"\n"
"  // Gyro aims the right stick -- adds to the C-stick when the client has\n"
"  // one (New 3DS), stands in for it alone when it doesn't (Old 3DS). See\n"
"  // the header comment for why \"aim\" (not \"substitute\") is correct as the\n"
"  // one default for both. Yaw drives stick X (turning the whole system\n"
"  // left/right), pitch drives stick Y (tilting the top screen toward/away\n"
"  // from the player).\n"
"  //\n"
"  // Every number below is a GUESS, least-to-most trustworthy:\n"
"  //  - deadzone 0.02 (2% of the 6000 dds full-scale below = 12 deg/s) is\n"
"  //    now backed by real hardware data (2026-08 field report): resting\n"
"  //    bias 1.8 deg/s, noise floor +-0.2 deg/s. 12 deg/s is comfortably\n"
"  //    clear of both, so it will not drift or false-trigger -- but that\n"
"  //    only proves it's SAFE, not that it's the right size for fine aiming.\n"
"  //    A large deadzone flattens exactly the small corrective nudges \"aim\"\n"
"  //    mode exists for. First thing to try if aim feels dead/sticky near\n"
"  //    centre: drop this toward roughly 2x the noise floor, e.g. 0.006-0.01\n"
"  //    (3.6-6 deg/s), and have someone actually aim with it before settling.\n"
"  //  - sensitivity 1.5 is carried over from the old substitute-only value\n"
"  //    and has NEVER been judged against the additive \"aim\" feel -- additive\n"
"  //    correction on top of a C-stick that's already moving may want to be\n"
"  //    lower (a twitchy gyro fighting the stick instead of refining it) or\n"
"  //    higher (barely perceptible on top of C-stick motion). Untouched here\n"
"  //    because changing it blind is exactly the \"guess the untested number\"\n"
"  //    problem this section exists to flag, not to hide.\n"
"  //  - the 6000 dds (600 deg/s) full-scale constant (mapping.c's\n"
"  //    APAD_GYRO_FULL_SCALE_DDS) that \"sensitivity\" multiplies on top of is\n"
"  //    a picked constant, not a spec value or a measured device limit --\n"
"  //    see mapping.c's own comment above compute_gyro_stick().\n"
"  \"gyro\": {\n"
"    \"mode\": \"aim\",\n"
"    \"stick\": \"right\",\n"
"    \"axis_x\": \"yaw\",\n"
"    \"axis_y\": \"pitch\",\n"
"    \"sensitivity\": 1.5,\n"
"    \"deadzone\": 0.02\n"
"  }\n"
"}\n";

/* server/profiles/generic-default.jsonc */
static const char ATTICPAD_PROFILE_GENERIC_DEFAULT[] =
"{\n"
"  // Generic fallback profile. An empty \"device\" match makes this a\n"
"  // wildcard: server/src/profiles.c's apad_profiles_match() returns the\n"
"  // first LOADED profile whose match_device is empty or a substring of\n"
"  // the connecting client's device_name, trying files in filename-sorted\n"
"  // order -- so a device-specific profile just needs a name that sorts\n"
"  // before this one alphabetically to be tried first (\"3ds-default.jsonc\"\n"
"  // already does; a hypothetical \"vita-default.jsonc\" would too).\n"
"  //\n"
"  // Every value below matches the compiled-in, always-available default\n"
"  // (server/src/profiles.c: set_builtin_default()) -- this file exists so\n"
"  // there is something to copy and edit for a new device, not because its\n"
"  // own settings differ from what the server does with no profile files\n"
"  // present at all. Missing/unparsable profile files are never fatal\n"
"  // (server/src/profiles.c logs and falls back to that same compiled-in\n"
"  // default) -- this file is a convenience and documentation aid, not\n"
"  // something the server depends on existing.\n"
"  \"profile\": \"generic-default\",\n"
"  \"match\": { \"device\": \"\" },\n"
"\n"
"  // Physical-position button naming (docs/PROTOCOL.md §5.4's default:\n"
"  // wire A, the right-hand face button, -> Xbox B; B, bottom, -> A; X,\n"
"  // top, -> Y; Y, left, -> X). This section is a no-op today -- the\n"
"  // built-in default already applies exactly this swap -- but is spelled\n"
"  // out so a copy of this file is easy to retarget for a new device:\n"
"  // change any one line to remap that button, or delete a line to fall\n"
"  // back to this same default for just that button.\n"
"  \"buttons\": {\n"
"    \"A\": \"B\", \"B\": \"A\", \"X\": \"Y\", \"Y\": \"X\",\n"
"    \"L\": \"LB\", \"R\": \"RB\"\n"
"  },\n"
"\n"
"  \"sticks\": {\n"
"    \"deadzone\": 0.08,\n"
"    \"curve\": \"quadratic\"\n"
"  },\n"
"\n"
"  \"triggers\": {\n"
"    \"deadzone\": 0.02\n"
"  },\n"
"\n"
"  // No touch or gyro substitution by default: a device with two real\n"
"  // sticks (APAD_CAP_STICK_L | APAD_CAP_STICK_R) never needs either, and\n"
"  // a device with one stick but no touch/gyro capability bits set has\n"
"  // nothing for these sections to substitute in the first place -- the\n"
"  // mapping engine gates every substitute on the client's own capability\n"
"  // mask regardless of what a profile asks for (server/src/mapping.c:\n"
"  // compute_stick() checks APAD_CAP_TOUCH / APAD_CAP_GYRO before ever\n"
"  // looking at these sections).\n"
"  \"touch\": { \"mode\": \"none\" },\n"
"  \"gyro\": { \"mode\": \"none\" }\n"
"}\n";

static const apad_builtin_profile ATTICPAD_BUILTIN_PROFILES[] = {
    { "built-in 3ds-default.jsonc", "3ds-default", ATTICPAD_PROFILE_3DS_DEFAULT },
    { "built-in generic-default.jsonc", "generic-default", ATTICPAD_PROFILE_GENERIC_DEFAULT },
};

#define ATTICPAD_BUILTIN_PROFILE_COUNT ((size_t)(2))

#endif /* ATTICPAD_HOST_COMMON_PROFILES_BUILTIN_H */
