/* server/host/common/profiles_builtin.h -- GENERATED, do not edit.
 *
 * Source: the .jsonc files in server/profiles/
 * Regenerate: scripts/support/gen_profiles_builtin.py (scripts/build.sh
 * does it, and CI fails if the committed copy differs).
 *
 * Why these are compiled in: a release is a single binary, and a server
 * that finds no profiles on disk would otherwise fall back to the
 * built-in default -- which on a 3DS means no touch-region triggers and
 * no gyro aim, while the client still draws both. Files on disk still
 * win; these are only the floor.
 */
#ifndef ATTICPAD_HOST_COMMON_PROFILES_BUILTIN_H
#define ATTICPAD_HOST_COMMON_PROFILES_BUILTIN_H

typedef struct {
    const char *label;   /* for diagnostics: where this came from */
    const char *name;    /* profile file stem, as on disk         */
    const char *text;    /* the JSONC itself                      */
} apad_builtin_profile;

/* server/profiles/3ds-default.jsonc */
static const char ATTICPAD_PROFILE_3DS_DEFAULT[] =
"{\n"
"  // 3DS default profile. Matches any HELLO whose decoded device_name\n"
"  // contains \"3DS\" (server/src/profiles.c: apad_profiles_match() does a\n"
"  // plain substring test against the whole device_name field). This one\n"
"  // file now covers BOTH 3DS variants -- see the \"gyro\" section below for\n"
"  // why a second, separately-matched profile isn't needed.\n"
"  //\n"
"  // docs/DESIGN.md §6.2's own worked example is for the Old 3DS: \"no C-stick, so\n"
"  // gyro drives the right stick.\" A New 3DS (caps=0x000004EF in the field\n"
"  // report this profile was written against) advertises APAD_CAP_STICK_R\n"
"  // AND APAD_CAP_GYRO together -- a working C-stick plus a gyro that, under\n"
"  // the old substitute-only priority chain (physical stick > touch\n"
"  // substitute > gyro substitute > centred), was read off the wire, mapped,\n"
"  // and then silently discarded every time because the physical stick\n"
"  // always won. Gyro aim had never once affected the pad on that hardware.\n"
"  //\n"
"  // \"mode\": \"aim\" (server/src/profiles.h's apad_gyro_mode_t) fixes this:\n"
"  // gyro now ADDS to the C-stick's own output (clamped to the axis range)\n"
"  // instead of only substituting for a missing one. On an Old 3DS, which\n"
"  // never sets APAD_CAP_STICK_R, the \"physical\" side of that sum is 0, so\n"
"  // the sum is just the gyro alone -- numerically identical to the old\n"
"  // substitute-only behaviour (server/src/mapping.c's compute_stick()\n"
"  // comment has the proof). That equivalence is exactly why one profile,\n"
"  // not two, is correct here: a second \"3ds-gyro-aim.jsonc\" matched on the\n"
"  // same \"3DS\" substring would only ever be reached if it sorted before\n"
"  // this file's name (server/src/profiles.c's apad_profiles_match() takes\n"
"  // the FIRST loaded profile whose match_device matches, in filename-sorted\n"
"  // order) -- an ambiguity with no user-facing way to pick between them,\n"
"  // since device_name comes from client firmware, not a user setting. This\n"
"  // file resolves that by being the one and only 3DS profile, correct for\n"
"  // both consoles.\n"
"  \"profile\": \"3ds-default\",\n"
"  \"match\": { \"device\": \"3DS\" },\n"
"\n"
"  // Identity button naming (wire \"A\" -> pad \"A\", and so on), matching\n"
"  // docs/DESIGN.md §6.2's own example verbatim. This deliberately does NOT use\n"
"  // the protocol's default physical-position swap (docs/PROTOCOL.md §5.4:\n"
"  // wire A, the right-hand face button, -> Xbox B, the right-hand Xbox\n"
"  // button in a *different* physical slot than A) -- §5.4 explicitly\n"
"  // reserves that choice for a profile: \"Per-profile A/B and X/Y swapping\n"
"  // is a mapping concern, not a protocol concern.\" Every 3DS game tells\n"
"  // the player to \"press A\"; keeping the label the player already\n"
"  // associates with that physical button outweighs matching an Xbox pad's\n"
"  // own physical face-button layout.\n"
"  \"buttons\": {\n"
"    \"A\": \"A\", \"B\": \"B\", \"X\": \"X\", \"Y\": \"Y\",\n"
"    \"L\": \"LB\", \"R\": \"RB\"\n"
"    // L3/R3/START/SELECT/HOME are left at the built-in default mapping\n"
"    // (LTHUMB/RTHUMB/START/BACK/GUIDE) -- nothing 3DS-specific to say\n"
"    // about them, and a 3DS HELLO never sets the L3/R3 bits anyway (no\n"
"    // clickable sticks on the hardware).\n"
"  },\n"
"\n"
"  // Circle Pad -> left stick. 8% deadzone (a physical circle pad's rest\n"
"  // position drifts more than a modern digital stick's centring spring),\n"
"  // quadratic curve: gentle near centre for fine aiming, full deflection\n"
"  // still reachable at the physical edge of travel.\n"
"  \"sticks\": {\n"
"    \"deadzone\": 0.08,\n"
"    \"curve\": \"quadratic\"\n"
"  },\n"
"\n"
"  // Bottom touchscreen, split into two soft on-screen shoulder triggers:\n"
"  // left half of the screen drives LT, right half drives RT, both analog.\n"
"  // \"analog: true\" ramps pressure with how far the thumb slides into its\n"
"  // half (see server/src/profiles.h's apad_touch_region comment for the\n"
"  // exact \"depth-into-region\" definition this engine uses -- these rects\n"
"  // are taller than they are wide, so depth reads as vertical travel: a\n"
"  // soft downward slide feels like squeezing a real analog trigger).\n"
"  // This is docs/DESIGN.md §6.2's own worked example, reproduced here.\n"
"  \"touch\": {\n"
"    \"mode\": \"regions\",\n"
"    \"regions\": [\n"
"      { \"rect\": [0.0, 0.0, 0.5, 1.0], \"emit\": \"LT\", \"analog\": true },\n"
"      { \"rect\": [0.5, 0.0, 1.0, 1.0], \"emit\": \"RT\", \"analog\": true }\n"
"    ]\n"
"  },\n"
"\n"
"  // Gyro aims the right stick -- adds to the C-stick when the client has\n"
"  // one (New 3DS), stands in for it alone when it doesn't (Old 3DS). See\n"
"  // the header comment for why \"aim\" (not \"substitute\") is correct as the\n"
"  // one default for both. Yaw drives stick X (turning the whole system\n"
"  // left/right), pitch drives stick Y (tilting the top screen toward/away\n"
"  // from the player).\n"
"  //\n"
"  // Every number below is a GUESS, least-to-most trustworthy:\n"
"  //  - deadzone 0.02 (2% of the 6000 dds full-scale below = 12 deg/s) is\n"
"  //    now backed by real hardware data (2026-08 field report): resting\n"
"  //    bias 1.8 deg/s, noise floor +-0.2 deg/s. 12 deg/s is comfortably\n"
"  //    clear of both, so it will not drift or false-trigger -- but that\n"
"  //    only proves it's SAFE, not that it's the right size for fine aiming.\n"
"  //    A large deadzone flattens exactly the small corrective nudges \"aim\"\n"
"  //    mode exists for. First thing to try if aim feels dead/sticky near\n"
"  //    centre: drop this toward roughly 2x the noise floor, e.g. 0.006-0.01\n"
"  //    (3.6-6 deg/s), and have someone actually aim with it before settling.\n"
"  //  - sensitivity 1.5 is carried over from the old substitute-only value\n"
"  //    and has NEVER been judged against the additive \"aim\" feel -- additive\n"
"  //    correction on top of a C-stick that's already moving may want to be\n"
"  //    lower (a twitchy gyro fighting the stick instead of refining it) or\n"
"  //    higher (barely perceptible on top of C-stick motion). Untouched here\n"
"  //    because changing it blind is exactly the \"guess the untested number\"\n"
"  //    problem this section exists to flag, not to hide.\n"
"  //  - the 6000 dds (600 deg/s) full-scale constant (mapping.c's\n"
"  //    APAD_GYRO_FULL_SCALE_DDS) that \"sensitivity\" multiplies on top of is\n"
"  //    a picked constant, not a spec value or a measured device limit --\n"
"  //    see mapping.c's own comment above compute_gyro_stick().\n"
"  \"gyro\": {\n"
"    \"mode\": \"aim\",\n"
"    \"stick\": \"right\",\n"
"    \"axis_x\": \"yaw\",\n"
"    \"axis_y\": \"pitch\",\n"
"    \"sensitivity\": 1.5,\n"
"    \"deadzone\": 0.02\n"
"  }\n"
"}\n";

/* server/profiles/ds-default.jsonc */
static const char ATTICPAD_PROFILE_DS_DEFAULT[] =
"{\n"
"  // Nintendo DS / DSi default profile. Matches any HELLO whose decoded\n"
"  // device_name CONTAINS \"AtticPad DS\" (server/src/profiles.c:\n"
"  // apad_profiles_match() does a plain substring test against the whole\n"
"  // device_name field). The DS client sends \"AtticPad DS\"; DSi mode sends\n"
"  // \"AtticPad DSi\", which also contains \"AtticPad DS\" as a substring, so\n"
"  // one file covers both without a second entry.\n"
"  //\n"
"  // TWO NAMING TRAPS, both load-bearing -- read profiles.c's own comment\n"
"  // above apad_profiles_load() before renaming this file or loosening the\n"
"  // match string:\n"
"  //\n"
"  // 1. FILENAME SORT ORDER. apad_profiles_match() returns the FIRST loaded\n"
"  //    profile whose match_device matches, and the Linux host loads profiles\n"
"  //    in filename-sorted order (server/src/profiles.c's comment above\n"
"  //    apad_profiles_load()). generic-default.jsonc's match_device is \"\"\n"
"  //    (an unconditional wildcard) -- so ANY device-specific profile whose\n"
"  //    filename sorts AFTER \"generic-default.jsonc\" is dead code, silently\n"
"  //    shadowed by the wildcard before it is ever tried. A more \"natural\"\n"
"  //    name for this file, \"nds-default.jsonc\", falls exactly into that\n"
"  //    trap: 'n' > 'g' in ASCII, so \"generic-default.jsonc\" would load\n"
"  //    first and this profile would never be reached, no error, no log line\n"
"  //    to say so. \"ds-default.jsonc\" was chosen because 'd' < 'g', which\n"
"  //    sorts it before generic-default.jsonc regardless of what else ships\n"
"  //    in this directory -- the same reason \"3ds-default.jsonc\" already\n"
"  //    works ('3' < 'g' too).\n"
"  //\n"
"  // 2. MATCH-STRING SPECIFICITY. The match string here is \"AtticPad DS\",\n"
"  //    not the bare substring \"DS\". \"DS\" alone would also match the 3DS\n"
"  //    client's own device_name (\"AtticPad 3DS\" contains \"DS\" inside\n"
"  //    \"3DS\") and any future device whose name happens to contain those two\n"
"  //    letters -- an accident waiting for the next profile added to this\n"
"  //    directory. It happens to be harmless FOR THE 3DS TODAY only because\n"
"  //    \"3ds-default.jsonc\" sorts before this file ('3' < 'd') and therefore\n"
"  //    wins the race regardless -- that is filename-order luck, not a\n"
"  //    property of the match string, and the next profile someone adds\n"
"  //    might not sort so conveniently. \"AtticPad DS\" is specific to this\n"
"  //    device family's actual advertised name and matches nothing else.\n"
"  \"profile\": \"ds-default\",\n"
"  \"match\": { \"device\": \"AtticPad DS\" },\n"
"\n"
"  // Identity button naming, same reasoning as 3ds-default.jsonc: every DS\n"
"  // game tells the player to \"press A\", and the DS's face-button layout is\n"
"  // already the same diamond as an Xbox pad's (A right, B bottom, X top,\n"
"  // Y left) -- unlike the 3DS, this isn't even overriding anything the\n"
"  // physical-position default would have picked differently by coincidence\n"
"  // of geometry, but it is spelled out explicitly rather than left to the\n"
"  // built-in default so a reader doesn't have to go check.\n"
"  \"buttons\": {\n"
"    \"A\": \"A\", \"B\": \"B\", \"X\": \"X\", \"Y\": \"Y\",\n"
"    \"L\": \"LB\", \"R\": \"RB\"\n"
"    // L3/R3/START/SELECT/HOME left at the built-in default mapping\n"
"    // (LTHUMB/RTHUMB/START/BACK/GUIDE) -- a DS HELLO never sets the L3/R3\n"
"    // bits (no clickable sticks on the hardware, same as the 3DS) and\n"
"    // START/SELECT are the DS's own labelled buttons, not stand-ins for\n"
"    // anything else.\n"
"  },\n"
"\n"
"  // No \"sticks\" or \"triggers\" section: this device's caps\n"
"  // (DPAD|FACE4|SHOULDER|TOUCH, +BATTERY on DSi) never set APAD_CAP_STICK_L,\n"
"  // APAD_CAP_STICK_R or APAD_CAP_TRIGGERS, so those profile sections would\n"
"  // be inert (mapping.c's compute_stick()/apply_trigger_axis() gate every\n"
"  // one of them on the client's own capability bit regardless of what a\n"
"  // profile asks for) and are omitted rather than shipped as decoration.\n"
"  //\n"
"  // The bottom touchscreen is the DS's ONLY stick-shaped input, so it\n"
"  // substitutes for the left stick (mapping.c's compute_stick(): touch\n"
"  // substitute only activates when APAD_CAP_STICK_L is ABSENT and\n"
"  // APAD_CAP_TOUCH is present -- exactly this device's caps). \"mode\":\n"
"  // \"absolute_stick\" was chosen over \"delta_stick\", and that choice is\n"
"  // specific to THIS device rather than a general touch-stick default:\n"
"  //\n"
"  //   - absolute_stick reads the touch point's raw screen position as the\n"
"  //     stick deflection directly (mapping.c's compute_touch_stick():\n"
"  //     dx = touches[0].x / 32768.0, already centred at screen-centre = 0\n"
"  //     by the wire's own normalisation, §5.2/§5.3) -- thumb position IS\n"
"  //     stick position, release snaps straight back to centre because\n"
"  //     touch_count drops to 0. This matches how a DS player already reads\n"
"  //     the bottom screen: it is a fixed drawing surface with a printed or\n"
"  //     imagined \"stick\" region, not a trackpad they expect to feel\n"
"  //     relative motion on. Games designed around the stylus (the\n"
"  //     touchscreen's actual original purpose) already train the player to\n"
"  //     think in absolute screen position, not relative drag.\n"
"  //   - delta_stick (anchor-on-first-touch, move-relative-from-there,\n"
"  //     return-to-centre on release -- see profiles.h's apad_touch_profile\n"
"  //     comment) is the alternative a user who dislikes this can switch to\n"
"  //     by editing this file: it behaves more like the analog nub on a\n"
"  //     laptop or the touch-stick corner of a Vita/PSP-style overlay, where\n"
"  //     the FIRST contact point becomes \"centre\" rather than the screen's\n"
"  //     geometric centre. That is a better fit for a player who rests their\n"
"  //     thumb somewhere comfortable rather than aiming for the middle of\n"
"  //     the screen every time -- worth trying if absolute mode feels too\n"
"  //     demanding of precise thumb placement in the exact centre.\n"
"  //   - Neither is \"regions\" (3ds-default.jsonc's touch use): the DS's\n"
"  //     touchscreen is this profile's ONLY stick, not a supplemental\n"
"  //     trigger surface next to a working circle pad, so there is nothing\n"
"  //     left over to spend on soft LT/RT zones without taking the stick\n"
"  //     away.\n"
"  //\n"
"  // deadzone 0.05 (small, not 0): a thumb resting near the screen's exact\n"
"  // geometric centre without meaning to move at all is far more likely on a\n"
"  // flat glass surface with no physical detent than on a spring-centred\n"
"  // circle pad (3ds-default.jsonc's stick deadzone is 0.08 for the OPPOSITE\n"
"  // reason -- a circle pad's rest position itself drifts) -- a small dead\n"
"  // disc around centre absorbs that without needing a big one, since unlike\n"
"  // a circle pad there is no spring pulling the thumb back to a known rest\n"
"  // position to drift away from. sensitivity 1.15: full stick deflection is\n"
"  // reached slightly before the touch point reaches the literal screen edge\n"
"  // (at magnitude 1/1.15 = ~87% of the way out), because the last few\n"
"  // millimetres of a 256x192 touchscreen sit under the bezel lip and are\n"
"  // uncomfortable to hold a thumb against for sustained analog movement.\n"
"  // GUESS, not measured against a real DS: both numbers are picked for the\n"
"  // same reason 3ds-default.jsonc's gyro numbers are flagged as guesses --\n"
"  // first things to tune against a real player if this feels dead near\n"
"  // centre (lower the deadzone) or requires uncomfortable full-reach thumb\n"
"  // stretches (raise the sensitivity further).\n"
"  \"touch\": {\n"
"    \"mode\": \"absolute_stick\",\n"
"    \"stick\": \"left\",\n"
"    \"sensitivity\": 1.15,\n"
"    \"deadzone\": 0.05\n"
"  },\n"
"\n"
"  // No gyro: the DS and DSi have none (APAD_CAP_GYRO is never set in this\n"
"  // device's caps).\n"
"  \"gyro\": { \"mode\": \"none\" }\n"
"}\n";

/* server/profiles/generic-default.jsonc */
static const char ATTICPAD_PROFILE_GENERIC_DEFAULT[] =
"{\n"
"  // Generic fallback profile. An empty \"device\" match makes this a\n"
"  // wildcard: server/src/profiles.c's apad_profiles_match() returns the\n"
"  // first LOADED profile whose match_device is empty or a substring of\n"
"  // the connecting client's device_name, trying files in filename-sorted\n"
"  // order -- so a device-specific profile just needs a name that sorts\n"
"  // before this one alphabetically to be tried first (\"3ds-default.jsonc\"\n"
"  // already does; a hypothetical \"vita-default.jsonc\" would too).\n"
"  //\n"
"  // Every value below matches the compiled-in, always-available default\n"
"  // (server/src/profiles.c: set_builtin_default()) -- this file exists so\n"
"  // there is something to copy and edit for a new device, not because its\n"
"  // own settings differ from what the server does with no profile files\n"
"  // present at all. Missing/unparsable profile files are never fatal\n"
"  // (server/src/profiles.c logs and falls back to that same compiled-in\n"
"  // default) -- this file is a convenience and documentation aid, not\n"
"  // something the server depends on existing.\n"
"  \"profile\": \"generic-default\",\n"
"  \"match\": { \"device\": \"\" },\n"
"\n"
"  // Physical-position button naming (docs/PROTOCOL.md §5.4's default:\n"
"  // wire A, the right-hand face button, -> Xbox B; B, bottom, -> A; X,\n"
"  // top, -> Y; Y, left, -> X). This section is a no-op today -- the\n"
"  // built-in default already applies exactly this swap -- but is spelled\n"
"  // out so a copy of this file is easy to retarget for a new device:\n"
"  // change any one line to remap that button, or delete a line to fall\n"
"  // back to this same default for just that button.\n"
"  \"buttons\": {\n"
"    \"A\": \"B\", \"B\": \"A\", \"X\": \"Y\", \"Y\": \"X\",\n"
"    \"L\": \"LB\", \"R\": \"RB\"\n"
"  },\n"
"\n"
"  \"sticks\": {\n"
"    \"deadzone\": 0.08,\n"
"    \"curve\": \"quadratic\"\n"
"  },\n"
"\n"
"  \"triggers\": {\n"
"    \"deadzone\": 0.02\n"
"  },\n"
"\n"
"  // No touch or gyro substitution by default: a device with two real\n"
"  // sticks (APAD_CAP_STICK_L | APAD_CAP_STICK_R) never needs either, and\n"
"  // a device with one stick but no touch/gyro capability bits set has\n"
"  // nothing for these sections to substitute in the first place -- the\n"
"  // mapping engine gates every substitute on the client's own capability\n"
"  // mask regardless of what a profile asks for (server/src/mapping.c:\n"
"  // compute_stick() checks APAD_CAP_TOUCH / APAD_CAP_GYRO before ever\n"
"  // looking at these sections).\n"
"  \"touch\": { \"mode\": \"none\" },\n"
"  \"gyro\": { \"mode\": \"none\" }\n"
"}\n";

static const apad_builtin_profile ATTICPAD_BUILTIN_PROFILES[] = {
    { "built-in 3ds-default.jsonc", "3ds-default", ATTICPAD_PROFILE_3DS_DEFAULT },
    { "built-in ds-default.jsonc", "ds-default", ATTICPAD_PROFILE_DS_DEFAULT },
    { "built-in generic-default.jsonc", "generic-default", ATTICPAD_PROFILE_GENERIC_DEFAULT },
};

#define ATTICPAD_BUILTIN_PROFILE_COUNT ((size_t)(3))

#endif /* ATTICPAD_HOST_COMMON_PROFILES_BUILTIN_H */
