#!/usr/bin/env bash
# scripts/support/check_vectors_wired.sh — the dead-vectors guard.
#
# Owned by scripts/ (ci-engineer), NOT by core/. What this catches, and why
# nothing else in the build catches it:
#
# core/testdata/vectors.h is generated by core/testdata/generate.py and
# consumed by core/src/selftest.c's apad_selftest_run(), the hidden
# L+R+Start conformance screen (docs/PROTOCOL.md §13) that is the ONLY
# diagnostic available on six platforms nobody can test on. Once, a whole
# new section of vectors.h (Section H: 14 committed apad_text_set_vectors /
# apad_text_get_vectors cases for a real docs/PROTOCOL.md §2 rule) landed
# with no driver loop in selftest.c referencing the new arrays. The build
# still compiled clean (unreferenced static consts, no warning) and the
# self-test still reported a perfectly green "990/990 passed, 0 failed" —
# it just never ran the 14 new cases. The bug they existed to catch was
# real and present the whole time.
#
# This is STRUCTURAL, not a one-off slip: whoever writes vectors.h is
# deliberately kept out of core/src/ (which owns selftest.c), because that
# independence is what makes the vectors worth
# anything as a conformance check. The direct consequence is that every
# future vectors.h section will arrive with no driver until someone
# SEPARATELY writes one — and neither cc's exit status nor
# apad_selftest_run()'s own pass/fail can ever say so, because from the
# inside a dead vector and an absent vector look identical: nothing ran, so
# nothing failed. Only the total case count moving is the tell, and nothing
# was watching it before this script.
#
# What this script checks: every top-level "table of test cases" array
# vectors.h declares — the shape `static const apad_vec_XXX
# apad_YYY_vectors[] = { ... }` — must be referenced by name somewhere in
# core/src/selftest.c. A grep-level check, deliberately: this only proves a
# driver loop EXISTS for each table, not that the loop is correct or that it
# walks every element — that is what actually running
# scripts/build.sh core (or CI's core-test job) and reading the printed
# total is for. The two checks are complementary, not redundant: this one
# catches "nobody wrote a driver at all" (the Section H failure mode, silent
# under every other check); the run catches "the driver has a bug", which
# shows up as a wrong total or a FAIL line.
#
# NOT every apad_vec_* name in vectors.h is in scope here. Individual byte
# arrays — apad_vec_*_bytes[], _packet[], _field[], _src[], _canonical[],
# apad_vec_hat_lut_ref[], etc. — are building blocks referenced FROM INSIDE
# a *_vectors[] struct array's initializers (e.g. apad_frame_vectors[]'s
# entries point at apad_vec_*_bytes[] by name in a struct literal). A driver
# loop iterates the *_vectors[] table, never those directly, so only names
# matching `apad_*_vectors[]` are the thing to check for a driver reference.
#
# Deliberately NOT here: making core/src/selftest.c auto-discover the
# arrays (e.g. some x-macro list vectors.h maintains and selftest.c
# includes). That file belongs to core/, not scripts/, and a build-time check
# from outside is the right tool for an ownership boundary that is
# deliberately kept — see the reasoning above.
#
# Usage: scripts/support/check_vectors_wired.sh
# Exit 0: every declared *_vectors[] table has a reference in selftest.c.
# Exit 1: at least one is dead (or the extraction itself found nothing,
#         which almost certainly means the pattern needs updating, not that
#         vectors.h is empty — see the "ZERO" check below).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../.." && pwd)"

VECTORS_H="${REPO_ROOT}/core/testdata/vectors.h"
SELFTEST_C="${REPO_ROOT}/core/src/selftest.c"

log()  { printf '== check_vectors_wired: %s ==\n' "$*"; }
fail() { printf 'check_vectors_wired: FAIL: %s\n' "$*" >&2; }

[[ -f "${VECTORS_H}" ]] || { fail "${VECTORS_H} does not exist"; exit 1; }
[[ -f "${SELFTEST_C}" ]] || { fail "${SELFTEST_C} does not exist"; exit 1; }

# Extract every top-level `static const <type> apad_..._vectors[]` name.
# -oE twice rather than one clever regex: the first pass anchors on the
# full declaration shape (so a plain array of bytes that happens to end in
# "_vectors" but isn't declared this way would not match); the second pulls
# just the identifier out of that match. Two passes over a ~2000 line
# generated header is not a place to optimize.
mapfile -t names < <(
  grep -oE '^static const [A-Za-z0-9_]+ apad_[A-Za-z0-9_]*_vectors\[\]' "${VECTORS_H}" \
    | grep -oE 'apad_[A-Za-z0-9_]*_vectors'
)

if [[ "${#names[@]}" -eq 0 ]]; then
  fail "found ZERO '*_vectors[]' table declarations in ${VECTORS_H}. Either vectors.h moved/changed shape and this script's pattern is stale, or core/testdata/generate.py stopped emitting any — either way this is the guard itself breaking, not a clean bill of health. Treating as a failure."
  exit 1
fi

log "${#names[@]} vector table(s) declared in core/testdata/vectors.h"

missing=()
for name in "${names[@]}"; do
  if ! grep -qE "\\b${name}\\b" "${SELFTEST_C}"; then
    missing+=("${name}")
  fi
done

if [[ "${#missing[@]}" -gt 0 ]]; then
  fail "${#missing[@]} of ${#names[@]} vector table(s) declared in core/testdata/vectors.h have NO reference anywhere in core/src/selftest.c — this is exactly the Section H failure mode (see this script's header): the array is compiled in, and apad_selftest_run() will never touch it, and will still report a clean pass."
  for m in "${missing[@]}"; do
    printf '  DEAD (never referenced in selftest.c): %s\n' "${m}" >&2
  done
  printf 'check_vectors_wired: fix is a driver loop in core/src/selftest.c referencing each name above (core-dev'"'"'s file, not scripts/'"'"'s) — see the existing st_vectors() loops in that file for the pattern.\n' >&2
  exit 1
fi

log "OK — all ${#names[@]} vector tables have a driver reference in core/src/selftest.c"
